apiVersion: v1
kind: Service

metadata:
  name: posts-srv

spec:
  type: NodePort # usually used for development purposes
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # exposed. http://localhost:4000
      targetPort: 4000 # used in index.js
